# Generated by Django 5.2.7 on 2025-10-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
    ]
