# Generated by Django 5.2.7 on 2025-10-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_usermodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='phone',
        ),
    ]
