# Generated by Django 5.2.7 on 2025-11-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_description', models.TextField()),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='book_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
